trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend-a/**
      - backend-b/**
      - k8s/**
      - pipelines/api.yml

pool:
  vmImage: ubuntu-latest

variables:
- group: db-secrets

- name: AZURE_SERVICE_CONNECTION
  value: "moath-sp-new"

- name: ACR_NAME
  value: "acrmoath"

- name: ACR_LOGIN_SERVER
  value: "acrmoath.azurecr.io"

- name: SONARQUBE_URL
  value: "http://20.64.246.3:9000"

- name: SONARQUBE_PROJECT_KEY
  value: "moath-api"

- name: SONARQUBE_PROJECT_NAME
  value: "moath-api"

stages:
- stage: Build
  displayName: "SAST + Build + Container Scan + Push"
  jobs:
  - job: BuildPush
    steps:
    - checkout: self

    # ---------- INSTALL SONAR SCANNER (WORKING VERSION) ----------
    - script: |
        set -e

        SCANNER_VERSION=5.0.1.3006
        FILE=sonar-scanner-$SCANNER_VERSION-linux-x64

        echo "Downloading SonarScanner $SCANNER_VERSION…"
        curl -L -o scanner.zip \
          https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/$FILE.zip

        echo "Unzipping…"
        unzip -q scanner.zip

        mv $FILE sonar-scanner
        chmod +x sonar-scanner/bin/sonar-scanner

        echo "SonarScanner installed successfully:"
        sonar-scanner/bin/sonar-scanner --version
      displayName: "Install SonarScanner CLI"


    # ---------- RUN SONAR SCAN ----------
    - script: |
        set -e

        ./sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=$(SONARQUBE_PROJECT_KEY) \
          -Dsonar.projectName="$(SONARQUBE_PROJECT_NAME)" \
          -Dsonar.host.url=$(SONARQUBE_URL) \
          -Dsonar.login=$(SONARQUBE_TOKEN) \
          -Dsonar.sources=backend-a,backend-b \
          -Dsonar.java.binaries=.
      displayName: "Run SonarQube Analysis"
      env:
        SONARQUBE_TOKEN: $(SONARQUBE_TOKEN)

    # ---------- LOGIN TO ACR ----------
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR_NAME)
      displayName: "Azure Login ACR"

    # ---------- BUILD DOCKER ----------
    - script: |
        docker build -t backend-a-local ./backend-a
        docker build -t backend-b-local ./backend-b
      displayName: "Build Docker Images"

    # ---------- INSTALL TRIVY ----------
    - script: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
          | sh -s -- -b /usr/local/bin
      displayName: "Install Trivy"

    # ---------- SCAN IMAGES ----------
    - script: trivy image --severity CRITICAL --exit-code 1 backend-a-local
      displayName: "Scan Backend A"
    - script: trivy image --severity CRITICAL --exit-code 1 backend-b-local
      displayName: "Scan Backend B"

    # ---------- PUSH ----------
    - script: |
        docker tag backend-a-local $(ACR_LOGIN_SERVER)/backend-a-moath:latest
        docker tag backend-b-local $(ACR_LOGIN_SERVER)/backend-b-moath:latest

        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:latest
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:latest
      displayName: "Push Images to ACR"



# =========================================================
# DEV STAGE
# =========================================================
- stage: Dev
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials -g rg-moath-dev -n aks-moath-dev --overwrite-existing
                kubectl apply -k k8s/overlays/dev


# =========================================================
# QA STAGE
# =========================================================
- stage: QA
  dependsOn: Dev
  condition: succeeded()
  jobs:
  - deployment: DeployQA
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials -g rg-moath-qa -n aks-moath-qa --overwrite-existing
                kubectl apply -k k8s/overlays/qa


# =========================================================
# PROD STAGE
# =========================================================
- stage: Prod
  dependsOn: QA
  condition: succeeded()
  jobs:
  - deployment: DeployProd
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials -g rg-moath-prod -n aks-moath-prod --overwrite-existing
                kubectl apply -k k8s/overlays/prod
