trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend-a/**
      - backend-b/**
      - k8s/**
      - pipelines/api.yml

pool:
  vmImage: ubuntu-latest

# =========================================================
# VARIABLES
# =========================================================
variables:
- group: db-secrets

- name: AZURE_SERVICE_CONNECTION
  value: "moath-sp-new"

- name: ACR_NAME
  value: "acrmoath"

- name: ACR_LOGIN_SERVER
  value: "acrmoath.azurecr.io"

# =========================================================
# BUILD STAGE
# =========================================================
stages:
- stage: Build
  displayName: "Build & Push Backend Images"
  jobs:
  - job: BuildPush
    displayName: "Docker Build & Push"
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: "Login to ACR"
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name $(ACR_NAME)

    - script: |
        set -e
        docker build -t $(ACR_LOGIN_SERVER)/backend-a-moath:latest ./backend-a
        docker build -t $(ACR_LOGIN_SERVER)/backend-b-moath:latest ./backend-b

        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:latest
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:latest
      displayName: "Build & Push Images"

# =========================================================
# DEV STAGE
# =========================================================
- stage: Dev
  displayName: "Deploy DEV"
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy DEV"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                az aks get-credentials -g rg-moath-dev -n aks-moath-dev --overwrite-existing

                # Ingress controller (install once)
                if ! kubectl get ns ingress-nginx >/dev/null 2>&1; then
                  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
                fi

                # WAIT for ingress controller + admission webhook
                kubectl rollout status deployment/ingress-nginx-controller \
                  -n ingress-nginx --timeout=180s

                kubectl wait -n ingress-nginx \
                  --for=condition=complete job/ingress-nginx-admission-create \
                  --timeout=120s

                kubectl wait -n ingress-nginx \
                  --for=condition=complete job/ingress-nginx-admission-patch \
                  --timeout=120s

                # Namespace
                kubectl apply -f k8s/namespaces/dev.yaml

                # DB Secret
                kubectl create secret generic postgres-secret-moath \
                  -n moath-webapp-dev \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_DEV)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                # Deploy app + ingress
                kubectl apply -k k8s/overlays/dev

                kubectl rollout restart deployment/backend-a-moath -n moath-webapp-dev
                kubectl rollout restart deployment/backend-b-moath -n moath-webapp-dev

                kubectl rollout status deployment/backend-a-moath -n moath-webapp-dev
                kubectl rollout status deployment/backend-b-moath -n moath-webapp-dev

# =========================================================
# QA STAGE
# =========================================================
- stage: QA
  displayName: "Deploy QA"
  dependsOn: Dev
  jobs:
  - deployment: DeployQA
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy QA"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                az aks get-credentials -g rg-moath-qa -n aks-moath-qa --overwrite-existing

                if ! kubectl get ns ingress-nginx >/dev/null 2>&1; then
                  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
                fi

                kubectl rollout status deployment/ingress-nginx-controller \
                  -n ingress-nginx --timeout=180s

                kubectl wait -n ingress-nginx \
                  --for=condition=complete job/ingress-nginx-admission-create \
                  --timeout=120s

                kubectl wait -n ingress-nginx \
                  --for=condition=complete job/ingress-nginx-admission-patch \
                  --timeout=120s

                kubectl apply -f k8s/namespaces/qa.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n moath-webapp-qa \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_QA)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/qa

                kubectl rollout restart deployment/backend-a-moath -n moath-webapp-qa
                kubectl rollout restart deployment/backend-b-moath -n moath-webapp-qa

                kubectl rollout status deployment/backend-a-moath -n moath-webapp-qa
                kubectl rollout status deployment/backend-b-moath -n moath-webapp-qa

# =========================================================
# PROD STAGE
# =========================================================
- stage: Prod
  displayName: "Deploy PROD"
  dependsOn: QA
  jobs:
  - deployment: DeployProd
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy PROD"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                az aks get-credentials -g rg-moath-prod -n aks-moath-prod --overwrite-existing

                if ! kubectl get ns ingress-nginx >/dev/null 2>&1; then
                  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
                fi

                kubectl rollout status deployment/ingress-nginx-controller \
                  -n ingress-nginx --timeout=180s

                kubectl wait -n ingress-nginx \
                  --for=condition=complete job/ingress-nginx-admission-create \
                  --timeout=120s

                kubectl wait -n ingress-nginx \
                  --for=condition=complete job/ingress-nginx-admission-patch \
                  --timeout=120s

                kubectl apply -f k8s/namespaces/prod.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n moath-webapp-prod \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_PROD)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/prod

                kubectl rollout restart deployment/backend-a-moath -n moath-webapp-prod
                kubectl rollout restart deployment/backend-b-moath -n moath-webapp-prod

                kubectl rollout status deployment/backend-a-moath -n moath-webapp-prod
                kubectl rollout status deployment/backend-b-moath -n moath-webapp-prod
