trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend-a/**
      - backend-b/**
      - k8s/**
      - pipelines/api.yml

pool:
  vmImage: ubuntu-latest

# =========================================================
# VARIABLES
# =========================================================
variables:
- group: db-secrets

- name: AZURE_SERVICE_CONNECTION
  value: "moath-sp-new"

- name: ACR_NAME
  value: "acrmoath"

- name: ACR_LOGIN_SERVER
  value: "acrmoath.azurecr.io"

# ---------- SONARQUBE VARIABLES ----------
- name: SONAR_PROJECT_KEY
  value: "moath-api"

- name: SONAR_PROJECT_NAME
  value: "moath-api"

- name: SONAR_SERVICE_CONNECTION
  value: "SonarQube-moath"

# =========================================================
# BUILD + SECURITY STAGE
# =========================================================
stages:
- stage: Build
  displayName: "Build, Scan and Push Backend Images"
  jobs:
  - job: BuildPush
    displayName: "Code Scan + Docker Build + Trivy"
    steps:
    - checkout: self

    # ---------- SAST: SONARQUBE ----------
    - task: SonarQubePrepare@4
      displayName: "Prepare SonarQube Analysis"
      inputs:
        SonarQube: $(SONAR_SERVICE_CONNECTION)
        scannerMode: "CLI"
        configMode: "manual"
        cliProjectKey: $(SONAR_PROJECT_KEY)
        cliProjectName: $(SONAR_PROJECT_NAME)
        cliSources: "backend-a,backend-b"

    - task: SonarQubeAnalyze@4
      displayName: "Run SonarQube SAST Analysis"

    - task: SonarQubePublish@4
      displayName: "Enforce Quality Gate"
      inputs:
        pollingTimeoutSec: "300"

    # ---------- LOGIN ACR ----------
    - task: AzureCLI@2
      displayName: "Login to ACR"
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name $(ACR_NAME)

    # ---------- DOCKER BUILD ----------
    - script: |
        set -e
        docker build -t backend-a-local ./backend-a
        docker build -t backend-b-local ./backend-b
      displayName: "Build Docker Images"

    # ---------- INSTALL TRIVY ----------
    - script: |
        set -e
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
          | sh -s -- -b /usr/local/bin
      displayName: "Install Trivy"

    # ---------- TRIVY SCANS ----------
    - script: |
        set -e
        trivy image \
          --severity CRITICAL \
          --exit-code 1 \
          backend-a-local
      displayName: "Trivy Scan Backend A (fail on CRITICAL)"

    - script: |
        set -e
        trivy image \
          --severity CRITICAL \
          --exit-code 1 \
          backend-b-local
      displayName: "Trivy Scan Backend B (fail on CRITICAL)"

    # ---------- TAG + PUSH ----------
    - script: |
        set -e
        docker tag backend-a-local $(ACR_LOGIN_SERVER)/backend-a-moath:latest
        docker tag backend-b-local $(ACR_LOGIN_SERVER)/backend-b-moath:latest

        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:latest
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:latest
      displayName: "Push Images to ACR"

# =========================================================
# DEV
# =========================================================
- stage: Dev
  displayName: "Deploy DEV"
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy DEV"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                az aks get-credentials -g rg-moath-dev -n aks-moath-dev --overwrite-existing

                if ! kubectl get ns ingress-nginx >/dev/null 2>&1; then
                  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
                fi

                kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx --timeout=180s

                kubectl apply -f k8s/namespaces/dev.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n moath-webapp-dev \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_DEV)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/dev

# =========================================================
# QA
# =========================================================
- stage: QA
  displayName: "Deploy QA"
  dependsOn: Dev
  jobs:
  - deployment: DeployQA
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy QA"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                az aks get-credentials -g rg-moath-qa -n aks-moath-qa --overwrite-existing

                kubectl apply -f k8s/namespaces/qa.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n moath-webapp-qa \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_QA)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/qa

# =========================================================
# PROD
# =========================================================
- stage: Prod
  displayName: "Deploy PROD"
  dependsOn: QA
  jobs:
  - deployment: DeployProd
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy PROD"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                az aks get-credentials -g rg-moath-prod -n aks-moath-prod --overwrite-existing

                kubectl apply -f k8s/namespaces/prod.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n moath-webapp-prod \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_PROD)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/prod
