trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend-a/**
      - backend-b/**
      - k8s/**
      - pipelines/api.yml

pool:
  vmImage: ubuntu-latest

variables:
- group: db-secrets

- name: AZURE_SERVICE_CONNECTION
  value: "moath-sp-new"

- name: ACR_NAME
  value: "acrmoath"

- name: ACR_LOGIN_SERVER
  value: "acrmoath.azurecr.io"

- name: AKS_NAME_DEV
  value: "aks-moath-dev"
- name: AKS_RG_DEV
  value: "rg-moath-dev"

- name: AKS_NAME_QA
  value: "aks-moath-qa"
- name: AKS_RG_QA
  value: "rg-moath-qa"

- name: AKS_NAME_PROD
  value: "aks-moath-prod"
- name: AKS_RG_PROD
  value: "rg-moath-prod"

- name: NAMESPACE_DEV
  value: "moath-webapp-dev"
- name: NAMESPACE_QA
  value: "moath-webapp-qa"
- name: NAMESPACE_PROD
  value: "moath-webapp-prod"

stages:
# =========================================================
# BUILD
# =========================================================
- stage: Build
  displayName: "Build & Push Images to ACR"
  jobs:
  - job: BuildPush
    displayName: "Build backend images"
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: "Login to ACR"
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name $(ACR_NAME)

    - script: |
        set -e
        docker build -t $(ACR_LOGIN_SERVER)/backend-a-moath:$(Build.BuildId) \
                     -t $(ACR_LOGIN_SERVER)/backend-a-moath:latest ./backend-a

        docker build -t $(ACR_LOGIN_SERVER)/backend-b-moath:$(Build.BuildId) \
                     -t $(ACR_LOGIN_SERVER)/backend-b-moath:latest ./backend-b

        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:$(Build.BuildId)
        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:latest
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:$(Build.BuildId)
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:latest
      displayName: "Docker Build & Push"

# =========================================================
# DEV
# =========================================================
- stage: Dev
  displayName: "Deploy DEV"
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy DEV"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az aks get-credentials -g $(AKS_RG_DEV) -n $(AKS_NAME_DEV) --overwrite-existing

                # ✅ Install ingress-nginx (idempotent) + WAIT
                kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
                kubectl rollout status deployment ingress-nginx-controller -n ingress-nginx --timeout=300s

                kubectl apply -f k8s/namespaces/dev.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n $(NAMESPACE_DEV) \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_DEV)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/dev

                kubectl rollout restart deployment/backend-a-moath -n $(NAMESPACE_DEV)
                kubectl rollout restart deployment/backend-b-moath -n $(NAMESPACE_DEV)

                kubectl rollout status deployment/backend-a-moath -n $(NAMESPACE_DEV)
                kubectl rollout status deployment/backend-b-moath -n $(NAMESPACE_DEV)

                # Optional safety check
                if kubectl get svc -n $(NAMESPACE_DEV) | grep LoadBalancer | grep backend; then
                  echo "❌ ERROR: Backend service exposed as LoadBalancer"
                  exit 1
                fi

# =========================================================
# QA
# =========================================================
- stage: QA
  displayName: "Deploy QA"
  dependsOn: Dev
  jobs:
  - deployment: DeployQA
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy QA"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az aks get-credentials -g $(AKS_RG_QA) -n $(AKS_NAME_QA) --overwrite-existing

                # ✅ Install ingress-nginx (idempotent) + WAIT
                kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
                kubectl rollout status deployment ingress-nginx-controller -n ingress-nginx --timeout=300s

                kubectl apply -f k8s/namespaces/qa.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n $(NAMESPACE_QA) \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_QA)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/qa

                kubectl rollout restart deployment/backend-a-moath -n $(NAMESPACE_QA)
                kubectl rollout restart deployment/backend-b-moath -n $(NAMESPACE_QA)

                kubectl rollout status deployment/backend-a-moath -n $(NAMESPACE_QA)
                kubectl rollout status deployment/backend-b-moath -n $(NAMESPACE_QA)

                # ✅ Quick check: ingress got an address
                kubectl get ingress -n $(NAMESPACE_QA)

# =========================================================
# PROD
# =========================================================
- stage: Prod
  displayName: "Deploy PROD"
  dependsOn: QA
  jobs:
  - deployment: DeployProd
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy PROD"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az aks get-credentials -g $(AKS_RG_PROD) -n $(AKS_NAME_PROD) --overwrite-existing

                # ✅ Install ingress-nginx (idempotent) + WAIT
                kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
                kubectl rollout status deployment ingress-nginx-controller -n ingress-nginx --timeout=300s

                kubectl apply -f k8s/namespaces/prod.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n $(NAMESPACE_PROD) \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_PROD)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/prod

                kubectl rollout restart deployment/backend-a-moath -n $(NAMESPACE_PROD)
                kubectl rollout restart deployment/backend-b-moath -n $(NAMESPACE_PROD)

                kubectl rollout status deployment/backend-a-moath -n $(NAMESPACE_PROD)
                kubectl rollout status deployment/backend-b-moath -n $(NAMESPACE_PROD)

                kubectl get ingress -n $(NAMESPACE_PROD)
