trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend-a/**
      - backend-b/**
      - k8s/**
      - pipelines/api.yml

pool:
  vmImage: ubuntu-latest

# 🔐 Variable group with DB secrets
variables:
- group: db-secrets

- name: AZURE_SERVICE_CONNECTION
  value: "moath-sp-new"

- name: ACR_NAME
  value: "acrmoath"

- name: ACR_LOGIN_SERVER
  value: "acrmoath.azurecr.io"

- name: AKS_NAME_DEV
  value: "aks-moath-dev"

- name: AKS_RG_DEV
  value: "rg-moath-dev"

- name: AKS_NAME_QA
  value: "aks-moath-qa"

- name: AKS_RG_QA
  value: "rg-moath-qa"

- name: AKS_NAME_PROD
  value: "aks-moath-prod"

- name: AKS_RG_PROD
  value: "rg-moath-prod"

- name: NAMESPACE_DEV
  value: "moath-webapp-dev"

- name: NAMESPACE_QA
  value: "moath-webapp-qa"

- name: NAMESPACE_PROD
  value: "moath-webapp-prod"

# =========================================================
# BUILD STAGE
# =========================================================
stages:
- stage: Build
  displayName: "Build & Push Images to ACR"
  jobs:
  - job: BuildPush
    displayName: "Build backend images"
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: "Login to ACR"
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR_NAME)

    - script: |
        docker build -t $(ACR_LOGIN_SERVER)/backend-a-moath:$(Build.BuildId) \
                     -t $(ACR_LOGIN_SERVER)/backend-a-moath:latest ./backend-a

        docker build -t $(ACR_LOGIN_SERVER)/backend-b-moath:$(Build.BuildId) \
                     -t $(ACR_LOGIN_SERVER)/backend-b-moath:latest ./backend-b

        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:$(Build.BuildId)
        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:latest
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:$(Build.BuildId)
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:latest
      displayName: "Docker Build & Push"

# =========================================================
# DEV STAGE
# =========================================================
- stage: Dev
  displayName: "Deploy DEV"
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy DEV"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az aks get-credentials -g $(AKS_RG_DEV) -n $(AKS_NAME_DEV) --overwrite-existing

                # Namespace
                kubectl apply -f k8s/namespaces/dev.yaml

                # 🔐 Create/update DB secret (DEV)
                kubectl create secret generic postgres-secret-moath \
                  -n $(NAMESPACE_DEV) \
                  --from-literal=POSTGRES_PASSWORD=$(DB_PASSWORD_DEV) \
                  --dry-run=client -o yaml | kubectl apply -f -

                # Deploy app
                kubectl apply -k k8s/overlays/dev

                # 🔄 Restart pods to pick up secret
                kubectl rollout restart deploy/backend-a-moath -n $(NAMESPACE_DEV)
                kubectl rollout restart deploy/backend-b-moath -n $(NAMESPACE_DEV)

                kubectl rollout status deploy/backend-a-moath -n $(NAMESPACE_DEV)
                kubectl rollout status deploy/backend-b-moath -n $(NAMESPACE_DEV)

# =========================================================
# QA STAGE
# =========================================================
- stage: QA
  displayName: "Deploy QA"
  dependsOn: Dev
  jobs:
  - deployment: DeployQA
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy QA"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az aks get-credentials -g $(AKS_RG_QA) -n $(AKS_NAME_QA) --overwrite-existing

                kubectl apply -f k8s/namespaces/qa.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n $(NAMESPACE_QA) \
                  --from-literal=POSTGRES_PASSWORD=$(DB_PASSWORD_QA) \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/qa

                kubectl rollout restart deploy/backend-a-moath -n $(NAMESPACE_QA)
                kubectl rollout restart deploy/backend-b-moath -n $(NAMESPACE_QA)

                kubectl rollout status deploy/backend-a-moath -n $(NAMESPACE_QA)
                kubectl rollout status deploy/backend-b-moath -n $(NAMESPACE_QA)

# =========================================================
# PROD STAGE
# =========================================================
- stage: Prod
  displayName: "Deploy PROD"
  dependsOn: QA
  jobs:
  - deployment: DeployProd
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy PROD"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az aks get-credentials -g $(AKS_RG_PROD) -n $(AKS_NAME_PROD) --overwrite-existing

                kubectl apply -f k8s/namespaces/prod.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n $(NAMESPACE_PROD) \
                  --from-literal=POSTGRES_PASSWORD=$(DB_PASSWORD_PROD) \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/prod

                kubectl rollout restart deploy/backend-a-moath -n $(NAMESPACE_PROD)
                kubectl rollout restart deploy/backend-b-moath -n $(NAMESPACE_PROD)

                kubectl rollout status deploy/backend-a-moath -n $(NAMESPACE_PROD)
                kubectl rollout status deploy/backend-b-moath -n $(NAMESPACE_PROD)
