trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend-a/**
      - backend-b/**
      - k8s/**
      - pipelines/api.yml

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_SERVICE_CONNECTION: "moath-sp-new"

  ACR_NAME: "acrmoath"
  ACR_LOGIN_SERVER: "acrmoath.azurecr.io"

  AKS_NAME_DEV: "aks-moath-dev"
  AKS_RG_DEV: "rg-moath-dev"

  AKS_NAME_QA: "aks-moath-qa"
  AKS_RG_QA: "rg-moath-qa"

  AKS_NAME_PROD: "aks-moath-prod"
  AKS_RG_PROD: "rg-moath-prod"

  NAMESPACE_DEV:  "moath-webapp-dev"
  NAMESPACE_QA:   "moath-webapp-qa"
  NAMESPACE_PROD: "moath-webapp-prod"

stages:
- stage: Build
  displayName: "Build & Push Images to ACR"
  jobs:
  - job: BuildPush
    displayName: "Build backend-a-moath & backend-b-moath"
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: "Login to ACR"
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name $(ACR_NAME)

    - script: |
        set -e
        docker build -t $(ACR_LOGIN_SERVER)/backend-a-moath:$(Build.BuildId) -t $(ACR_LOGIN_SERVER)/backend-a-moath:latest ./backend-a
        docker build -t $(ACR_LOGIN_SERVER)/backend-b-moath:$(Build.BuildId) -t $(ACR_LOGIN_SERVER)/backend-b-moath:latest ./backend-b

        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:$(Build.BuildId)
        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:latest
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:$(Build.BuildId)
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:latest
      displayName: "Docker Build & Push"

- stage: Dev
  displayName: "Deploy DEV"
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    displayName: "Deploy to AKS DEV"
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy DEV via Kustomize"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az aks get-credentials -g $(AKS_RG_DEV) -n $(AKS_NAME_DEV) --overwrite-existing

                # Install ingress-nginx once per cluster (safe if already installed)
                kubectl get ns ingress-nginx >/dev/null 2>&1 || kubectl apply -f k8s/cluster/ingress-nginx/namespace-ingress.yaml
                kubectl apply -f k8s/cluster/ingress-nginx/nginx-controller.yaml -n ingress-nginx
                kubectl apply -f k8s/cluster/ingress-nginx/nginx-service.yaml -n ingress-nginx

                # Deploy app (namespace comes from overlay)
                kubectl apply -f k8s/namespaces/dev.yaml

                kubectl apply -k k8s/overlays/dev

                kubectl get pods -n $(NAMESPACE_DEV)
                kubectl get svc  -n $(NAMESPACE_DEV)
                kubectl get ingress -n $(NAMESPACE_DEV)

- stage: QA
  displayName: "Deploy QA"
  dependsOn: Dev
  jobs:
  - deployment: DeployQA
    displayName: "Deploy to AKS QA"
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy QA via Kustomize"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az aks get-credentials -g $(AKS_RG_QA) -n $(AKS_NAME_QA) --overwrite-existing

                kubectl get ns ingress-nginx >/dev/null 2>&1 || kubectl apply -f k8s/cluster/ingress-nginx/namespace-ingress.yaml
                kubectl apply -f k8s/cluster/ingress-nginx/nginx-controller.yaml -n ingress-nginx
                kubectl apply -f k8s/cluster/ingress-nginx/nginx-service.yaml -n ingress-nginx
                kubectl apply -f k8s/namespaces/qa.yaml
                kubectl apply -k k8s/overlays/qa

                kubectl get pods -n $(NAMESPACE_QA)
                kubectl get svc  -n $(NAMESPACE_QA)
                kubectl get ingress -n $(NAMESPACE_QA)

- stage: Prod
  displayName: "Deploy PROD"
  dependsOn: QA
  jobs:
  - deployment: DeployProd
    displayName: "Deploy to AKS PROD"
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy PROD via Kustomize"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az aks get-credentials -g $(AKS_RG_PROD) -n $(AKS_NAME_PROD) --overwrite-existing

                kubectl get ns ingress-nginx >/dev/null 2>&1 || kubectl apply -f k8s/cluster/ingress-nginx/namespace-ingress.yaml
                kubectl apply -f k8s/cluster/ingress-nginx/nginx-controller.yaml -n ingress-nginx
                kubectl apply -f k8s/cluster/ingress-nginx/nginx-service.yaml -n ingress-nginx
                kubectl apply -f k8s/namespaces/prod.yaml
                kubectl apply -k k8s/overlays/prod

                kubectl get pods -n $(NAMESPACE_PROD)
                kubectl get svc  -n $(NAMESPACE_PROD)
                kubectl get ingress -n $(NAMESPACE_PROD)
