trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend-a/**
      - backend-b/**
      - k8s/**
      - pipelines/api.yml

pool:
  vmImage: ubuntu-latest

# 🔐 Variable group with DB secrets
variables:
- group: db-secrets

- name: AZURE_SERVICE_CONNECTION
  value: "moath-sp-new"

- name: ACR_NAME
  value: "acrmoath"

- name: ACR_LOGIN_SERVER
  value: "acrmoath.azurecr.io"

- name: AKS_NAME_DEV
  value: "aks-moath-dev"
- name: AKS_RG_DEV
  value: "rg-moath-dev"

- name: AKS_NAME_QA
  value: "aks-moath-qa"
- name: AKS_RG_QA
  value: "rg-moath-qa"

- name: AKS_NAME_PROD
  value: "aks-moath-prod"
- name: AKS_RG_PROD
  value: "rg-moath-prod"

- name: NAMESPACE_DEV
  value: "moath-webapp-dev"
- name: NAMESPACE_QA
  value: "moath-webapp-qa"
- name: NAMESPACE_PROD
  value: "moath-webapp-prod"

# =========================================================
# BUILD STAGE
# =========================================================
stages:
- stage: Build
  displayName: "Build & Push Images"
  jobs:
  - job: BuildPush
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: "Login to ACR"
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR_NAME)

    - script: |
        docker build -t $(ACR_LOGIN_SERVER)/backend-a-moath:latest ./backend-a
        docker build -t $(ACR_LOGIN_SERVER)/backend-b-moath:latest ./backend-b

        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:latest
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:latest
      displayName: "Build & Push Images"

# =========================================================
# DEV
# =========================================================
- stage: Dev
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Deploy DEV"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials -g $(AKS_RG_DEV) -n $(AKS_NAME_DEV) --overwrite-existing

                kubectl get ns ingress-nginx || \
                kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml

                kubectl apply -f k8s/namespaces/dev.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n $(NAMESPACE_DEV) \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_DEV)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/dev

# =========================================================
# QA
# =========================================================
- stage: QA
  dependsOn: Dev
  jobs:
  - deployment: DeployQA
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Deploy QA"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials -g $(AKS_RG_QA) -n $(AKS_NAME_QA) --overwrite-existing

                kubectl apply -f k8s/namespaces/qa.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n $(NAMESPACE_QA) \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_QA)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/qa

# =========================================================
# PROD
# =========================================================
- stage: Prod
  dependsOn: QA
  jobs:
  - deployment: DeployProd
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Deploy PROD"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials -g $(AKS_RG_PROD) -n $(AKS_NAME_PROD) --overwrite-existing

                kubectl apply -f k8s/namespaces/prod.yaml

                kubectl create secret generic postgres-secret-moath \
                  -n $(NAMESPACE_PROD) \
                  --from-literal=POSTGRES_PASSWORD="$(DB_PASSWORD_PROD)" \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -k k8s/overlays/prod
