trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend-a/**
      - backend-b/**
      - k8s/**
      - pipelines/api.yml

pool:
  vmImage: ubuntu-latest

variables:
  # Azure
  AZURE_SERVICE_CONNECTION: "moath-sp-new"

  # ACR (shared infra)
  ACR_NAME: "acrmoath"
  ACR_LOGIN_SERVER: "acrmoath.azurecr.io"

  # AKS - DEV
  AKS_NAME_DEV: "aks-moath-dev"
  AKS_RG_DEV: "rg-moath-dev"

  # AKS - QA
  AKS_NAME_QA: "aks-moath-qa"
  AKS_RG_QA: "rg-moath-qa"

  # AKS - PROD
  AKS_NAME_PROD: "aks-moath-prod"
  AKS_RG_PROD: "rg-moath-prod"

  # Kubernetes
  NAMESPACE: "moath-webapp"

# =========================================================
# BUILD & PUSH (ONCE)
# =========================================================
stages:
- stage: Build
  displayName: "Build & Push Images to ACR"
  jobs:
  - job: BuildPush
    displayName: "Build backend-a-moath & backend-b-moath"
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: "Login to ACR"
      inputs:
        azureSubscription: $(AZURE_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name $(ACR_NAME)

    - script: |
        set -e

        echo "Building backend-a-moath..."
        docker build \
          -t $(ACR_LOGIN_SERVER)/backend-a-moath:$(Build.BuildId) \
          -t $(ACR_LOGIN_SERVER)/backend-a-moath:latest \
          ./backend-a

        echo "Building backend-b-moath..."
        docker build \
          -t $(ACR_LOGIN_SERVER)/backend-b-moath:$(Build.BuildId) \
          -t $(ACR_LOGIN_SERVER)/backend-b-moath:latest \
          ./backend-b

        echo "Pushing backend-a-moath..."
        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:$(Build.BuildId)
        docker push $(ACR_LOGIN_SERVER)/backend-a-moath:latest

        echo "Pushing backend-b-moath..."
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:$(Build.BuildId)
        docker push $(ACR_LOGIN_SERVER)/backend-b-moath:latest
      displayName: "Docker Build & Push"

# =========================================================
# DEV DEPLOY
# =========================================================
- stage: Dev
  displayName: "Deploy DEV"
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    displayName: "Deploy to AKS DEV"
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy DEV via Kustomize"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                az aks get-credentials \
                  -g $(AKS_RG_DEV) \
                  -n $(AKS_NAME_DEV) \
                  --overwrite-existing

                kubectl create namespace $(NAMESPACE) \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -n $(NAMESPACE) -k k8s/overlays/dev

                kubectl get pods -n $(NAMESPACE)
                kubectl get svc  -n $(NAMESPACE)

# =========================================================
# QA DEPLOY
# =========================================================
- stage: QA
  displayName: "Deploy QA"
  dependsOn: Dev
  jobs:
  - deployment: DeployQA
    displayName: "Deploy to AKS QA"
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy QA via Kustomize"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                az aks get-credentials \
                  -g $(AKS_RG_QA) \
                  -n $(AKS_NAME_QA) \
                  --overwrite-existing

                kubectl create namespace $(NAMESPACE) \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -n $(NAMESPACE) -k k8s/overlays/qa

                kubectl get pods -n $(NAMESPACE)
                kubectl get svc  -n $(NAMESPACE)

# =========================================================
# PROD DEPLOY
# =========================================================
- stage: Prod
  displayName: "Deploy PROD"
  dependsOn: QA
  jobs:
  - deployment: DeployProd
    displayName: "Deploy to AKS PROD"
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: "latest"

          - task: AzureCLI@2
            displayName: "Deploy PROD via Kustomize"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                az aks get-credentials \
                  -g $(AKS_RG_PROD) \
                  -n $(AKS_NAME_PROD) \
                  --overwrite-existing

                kubectl create namespace $(NAMESPACE) \
                  --dry-run=client -o yaml | kubectl apply -f -

                kubectl apply -n $(NAMESPACE) -k k8s/overlays/prod

                kubectl get pods -n $(NAMESPACE)
                kubectl get svc  -n $(NAMESPACE)
